# Generated by Django 2.1.7 on 2019-03-06 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(auto_now=True, verbose_name='Date Requested')),
                ('gid', models.CharField(max_length=128, verbose_name='Google ID')),
                ('name', models.CharField(default='New Project', max_length=256, verbose_name='Name')),
                ('status', models.CharField(default='new', max_length=32, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
