# Generated by Django 2.1.7 on 2019-03-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190306_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gid',
            field=models.CharField(max_length=128, null=True, verbose_name='Google ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(null=True, verbose_name='Sheet URL'),
        ),
    ]
