# Generated by Django 2.1.7 on 2019-03-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190306_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(null=True, verbose_name='Progress'),
        ),
        migrations.AddField(
            model_name='project',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Size'),
        ),
    ]
