# Generated by Django 2.1.5 on 2019-03-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_account_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='priority',
            field=models.CharField(
                blank=True, default=10, max_length=8, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='rating',
            field=models.CharField(
                blank=True, default=10, max_length=8, null=True, verbose_name='Rating'),
        ),
    ]
