# Generated by Django 2.1.7 on 2019-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190328_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cleaned',
            field=models.BooleanField(default=False, verbose_name='Cleaned'),
        ),
    ]
