# Generated by Django 2.2.1 on 2019-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_page")]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(
                blank=True, max_length=32000, null=True, verbose_name="Page Content"
            ),
        )
    ]
