# Generated by Django 2.2.1 on 2019-07-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_historicaladvantage_historicalcomment_historicalcompetitor_historicalinsight_historicalpage_historic'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='pricing',
            field=models.TextField(default='No pricing information available.', max_length=2048, verbose_name='Pricing Details'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='strengths',
            field=models.TextField(default='No key strengths added.', max_length=2048, verbose_name='Key Strengths'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='wins',
            field=models.TextField(default='No replacement wins recorded.', max_length=2048, verbose_name='Replacement Wins'),
        ),
        migrations.AddField(
            model_name='historicalcompetitor',
            name='pricing',
            field=models.TextField(default='No pricing information available.', max_length=2048, verbose_name='Pricing Details'),
        ),
        migrations.AddField(
            model_name='historicalcompetitor',
            name='strengths',
            field=models.TextField(default='No key strengths added.', max_length=2048, verbose_name='Key Strengths'),
        ),
        migrations.AddField(
            model_name='historicalcompetitor',
            name='wins',
            field=models.TextField(default='No replacement wins recorded.', max_length=2048, verbose_name='Replacement Wins'),
        ),
    ]
