# Generated by Django 2.2.1 on 2019-07-16 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20190716_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='script',
            field=models.TextField(max_length=2048, verbose_name='Script'),
        ),
        migrations.AlterField(
            model_name='historicaladvantage',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicaladvantage',
            name='script',
            field=models.TextField(max_length=2048, verbose_name='Script'),
        ),
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('datestamp', models.DateField(auto_now_add=True, verbose_name='Datestamp')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('script', models.TextField(max_length=2048, verbose_name='Script')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', related_query_name='objection', to='api.Competitor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalObjection',
            fields=[
                ('datestamp', models.DateField(blank=True, editable=False, verbose_name='Datestamp')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('script', models.TextField(max_length=2048, verbose_name='Script')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('competitor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='objection', to='api.Competitor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical objection',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
