# Generated by Django 2.2.1 on 2019-07-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_historicalproperty_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='competitor',
        ),
        migrations.DeleteModel(
            name='HistoricalProperty',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
