# Generated by Django 2.1.5 on 2019-01-17 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, verbose_name='Access Token')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('base', models.URLField(verbose_name='Base URL')),
                ('description', models.TextField(max_length=256, verbose_name='Description')),
                ('auth', models.PositiveSmallIntegerField(choices=[(1, 'none'), (2, 'basic'), (3, 'header'), (4, 'params')], default=(1, 'none'), verbose_name='Auth Method')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=512, null=True, verbose_name='Password')),
                ('key', models.CharField(blank=True, max_length=512, null=True, verbose_name='Key')),
                ('keyname', models.CharField(blank=True, max_length=256, null=True, verbose_name='Key Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('path', models.CharField(max_length=256, verbose_name='Path from Base')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('auth', models.BooleanField(default=False, verbose_name='Auth Required')),
                ('method', models.PositiveSmallIntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'PATCH'), (5, 'DELETE')], default=(2, 'POST'), verbose_name='HTTP Method')),
                ('headers', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Request Headers')),
                ('params', models.CharField(blank=True, max_length=2048, null=True, verbose_name='URL Parameters')),
                ('body', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Request Body')),
                ('calls', models.IntegerField(default=0, verbose_name='Calls')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.API')),
            ],
        ),
    ]
