# Generated by Django 2.1.5 on 2019-01-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='body',
            field=models.CharField(blank=True, default='{}', max_length=2048, null=True, verbose_name='Request Body'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='headers',
            field=models.CharField(blank=True, default='{}', max_length=2048, null=True, verbose_name='Request Headers'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='params',
            field=models.CharField(blank=True, default='{}', max_length=2048, null=True, verbose_name='URL Parameters'),
        ),
    ]
