# Generated by Django 2.1.5 on 2019-01-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190117_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True, verbose_name='Time')),
                ('traceback', models.TextField(max_length=8192, verbose_name='Captured Traceback')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.API')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Endpoint')),
            ],
        ),
    ]
