# Generated by Django 2.1.5 on 2019-01-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='targets',
            field=models.CharField(blank=True, default=[], max_length=2048, null=True, verbose_name='Data Targets'),
        ),
    ]
