# Generated by Django 2.1.7 on 2019-03-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_endpoint_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
